### ISSUE TITLE
Increase user interaction

### ISSUE THREAD

**Issue by tmarkec** [tmarkec/My-First-Agile-Project#3]
In order to **provide anonymous feedback** as a **user** I can **choose to hide my identity in the poll response**.

### Acceptance Criteria:
 - Acceptance criteria 1:  Option should be provided as checkbox
 - Acceptance criteria 2: The checkbox should be checked by default
 - Acceptance criteria 3: Option should appear next to submit button
 - Acceptance criteria 4: After submitting the default submission confirmation should be adjusted to include the user name.
 
### Tasks
- [ ] Update the view: the poll design(html & css)
- [ ] Update controler function
- [ ] Create new field in the model to track username
- [ ] Update unit test scripts
- [ ] Test the functionality
